global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ingestion-service'
    static_configs:
      - targets: ['host.docker.internal:3001']

  - job_name: 'worker-service'
    static_configs:
      - targets: ['host.docker.internal:3002']
